### ISSUE TITLE
Scripts in package.json

### ISSUE THREAD

**Issue by 1TaylanOzturk** [Oscargjane/Guess-the-Number#1]
This is the command which I mention: `npm run clean && parcel public/index.html --out-dir development -p 3000 --open`
(It's in "scripts" key of package.json)

What does this command do ? How does it work ?

**Comment by Oscargjane** [comment]
1. Run the cleanup script that removes the development and cache folders.
2. Starts a development server from the specified input (public / index.html) on port 3000, which is written to the output directory: development using the `--out-dir `parameter and the input is automatically opened in the browser with the `--open` parameter.
